module DBOS.SystemDB
  ( Pool.Pool,
    Postgres.DbosDbError (..),
    Postgres.WorkflowStartDecision (..),
    Postgres.acquirePool,
    Postgres.releasePool,
    Postgres.runDb,
    Postgres.runDbOrFail,
    Postgres.fetchMigrationVersion,
    Postgres.fetchWorkflowExecutionRow,
    Postgres.fetchWorkflowStatus,
    Postgres.fetchOperationCheckpoint,
    Postgres.fetchNotification,
    Postgres.tryStartWorkflow,
    Postgres.updateWorkflowOutcome,
    Postgres.recordOperationOutput,
    Postgres.recordOperationError,
    Postgres.recordSleep,
    Postgres.setEvent,
    Postgres.getEvent,
    Postgres.getEventBlocking,
    Postgres.sendMessage,
    Postgres.sendMessages,
    Postgres.recvMessage,
    Postgres.listWorkflowIdsByName,
    Postgres.registerQueue,
    Postgres.releaseWorkflowClaim,
    Postgres.fetchQueueWorkerConcurrency,
    Postgres.updateQueueWorkerConcurrency,
    Postgres.enqueueWorkflow,
    Postgres.dequeueWorkflows,
    Postgres.fetchWorkflowStatuses,
    Postgres.reenqueueForRecovery,
    IdempotencyKey (..),
    MessageUUID (..),
    NotificationRow (..),
    QueueConflict (..),
    QueueName (..),
    SendMessage (..),
    Topic (..),
    internalQueueName,
    message,
    messageTo,
    messageUUIDForSend,
    notificationRowForMessage,
    nullTopicSentinel,
  )
where

import DBOS.SystemDB.Postgres qualified as Postgres
import Hasql.Pool qualified as Pool
import DBOS.SystemDB.Types
  ( IdempotencyKey (..),
    MessageUUID (..),
    NotificationRow (..),
    QueueConflict (..),
    QueueName (..),
    SendMessage (..),
    Topic (..),
    internalQueueName,
    message,
    messageTo,
    messageUUIDForSend,
    notificationRowForMessage,
    nullTopicSentinel,
  )
