module DBOS.Transact
  ( -- * Workflow executions
    ApplicationVersion (..),
    Duration (..),
    durationAsMillis,
    millisDuration,
    secondsDuration,
    Timestamp (..),
    WorkflowDelay (..),
    WorkflowId (..),
    WorkflowName (..),
    WorkflowStatus (..),
    WorkflowStatusDecodeError (..),
    isTerminal,
    parseWorkflowStatus,
    workflowStatusText,

    -- * Durable steps
    StepError (..),
    runWorkflowStep,
    runNestedStep,
    pendingWorkflowStep,
    pendingWorkflowStepWith,
    runWorkflowStepWith,
    stepOptionsDefault,
    StepOptions (..),
    sleepWorkflowStep,
    pendingSleep,
    sleepPlain,
    setEvent,
    getEvent,
    pendingGetEvent,
    pendingSetEvent,
    Message (..),
    Forks (..),
    SendOptions (..),
    sendOptionsDefault,
    SendBulkOptions (..),
    sendBulkOptionsDefault,
    send,
    sendWith,
    sendBulk,
    sendBulkWith,
    recv,

    -- * Transactional steps (datasource.rs — port's own seam, ADR-0021)
    IsolationLevel (..),
    TransactionConfig (..),
    transactionConfigDefault,
    RecordedOutcome (..),
    Tx (..),
    DataSource (..),
    runTransaction,
    runTransactionOutside,
    AppDataSource,
    acquireAppDataSource,
    acquireAppDataSourceIn,
    acquireAppDataSourceInFromEnv,
    releaseAppDataSource,
    verifyAppDataSource,
    runAppSession,
    toDataSource,
    beginSql,

    -- * Durable value codec
    CodecError (..),
    Serialization (..),
    SerializedWorkflowValue (..),
    decodeWorkflowValue,
    encodeWorkflowValue,

    -- * Domain-event tracing (no logging library)
    Tracer,
    SomeTracer (..),
    mkTracer,
    nullTracer,
    runTracer,
    contramap,
    TimedFastLogger,
    LoggerBackend (..),
    newLoggerBackend,
    acquireLoggerBackend,
    ThreadIdCache,
    fastLoggerTracer,
    ioTracer,
    LogSeverity (..),
    showSeverity,
    parseSeverity,
    LogEvent (..),
    EngineEvent (..),
    SysdbEvent (..),
    WorkflowEvent (..),
    QueueEvent (..),
    ManagementEvent (..),
    WaitEvent (..),
    SleepEvent (..),
    TransactionEvent (..),

    -- * Configuration and identity (config.rs, identity.rs)
    Config (..),
    Serializer (..),
    serializerName,
    configNew,
    configFromEnv,
    validateConfig,
    renderTransactError,
    Environment (..),
    Identity (..),
    readEnvironment,
    -- * Instance lifecycle (instance.rs)
    DBOS,
    newDBOS,
    launchOn,
    Executor,
    isLaunched,
    launch,
    launchWithEnvironment,
    shutdown,
    registerDBOSWorkflow,
    registerDBOSWorkflowRef,
    registerDBOSDataSource,
    clearDBOSCheckpoints,
    runDBOSWorkflow,
    startDBOSWorkflowRef,
    runDBOSWorkflowRef,
    enqueueDBOSWorkflow,
    retrieveWorkflow,
    getWorkflowEvent,
    sendWorkflowMessage,
    sendWorkflowMessages,
    listWorkflowIdsByName,
    fetchWorkflowStatuses,
    dequeueDBOSWorkflows,
    cancelWorkflows,
    cancelWorkflowsInWorkflow,
    resumeWorkflows,
    resumeWorkflowsInWorkflow,
    setWorkflowDelay,
    deleteWorkflows,
    deleteWorkflowsInWorkflow,
    forkWorkflows,
    forkWorkflowsInWorkflow,
    forkFrom,
    forkFromInWorkflow,
    updateWorkflowAttributes,
    listWorkflows,
    listWorkflowsInWorkflow,
    selectWorkflow,
    joinWorkflows,
    waitForWorkflow,
    waitForFirstWorkflow,
    waitForWorkflows,
    -- * Checkpoint placement (checkpoint.rs)
    StepPlacement (..),
    StepDurability (..),
    PendingStep (..),
    -- * Workflow handles (handle.rs)
    WorkflowHandle (..),
    Provenance (..),
    pollingHandle,
    handleWorkflowId,
    handleStatus,
    handleResult,
    awaitChild,
    pendingAwait,
    -- * Durable races (select.rs)
    Racing (..),
    Recording (..),
    Branches (..),
    SelectArm (..),
    Winner (..),
    selectStep,
    -- * Client (client.rs)
    Client (..),
    ClientConfig (..),
    clientConfigNew,
    clientConfigFromEnv,
    validateClientConfig,
    clientOutcomePollInterval,
    connectClient,
    closeClient,
    clientAppName,
    EnqueueOptions (..),
    enqueueOptionsNew,
    enqueueOptionsOn,
    enqueueClientWorkflow,
    enqueueClientWorkflowWith,
    retrieveClientWorkflow,
    workflowStatusClient,
    clientSendMessage,
    clientSendMessages,
    clientGetEvent,
    clientCancelWorkflows,
    clientResumeWorkflows,
    clientDeleteWorkflows,
    clientForkWorkflows,
    clientListApplicationVersions,
    clientLatestApplicationVersion,
    clientPromoteVersion,
    clientListWorkflows,
    -- * Connection (connection.rs): engine-internal, no client entry.
    -- * Ambient context
    StepStatus (..),
    firstStepStatus,
    StepMarker (..),
    -- * Scoped workflow contexts
    WorkflowCtx,
    StepCtx,
    withWorkflow,
    withStep,
    nextWorkflowStepId,
    nextWorkflowMarker,
    workflowCtxId,
    stepCtxId,
    stepCtxStatus,
    stepCtxWorkflow,
    stepCtxCancellationToken,
    -- * Workflow registry and runner
    Error (..),
    EngineOnly,
    DurableError,
    Failure (..),
    application,
    mapApplication,
    liftEngine,
    controlOf,
    encodeErrorText,
    decodeErrorText,
    BackendError (..),
    WorkflowKey (..),
    newWorkflowKey,
    WorkflowRef,
    registerWorkflowRef,
    registerTypedWorkflow,
    Registry,
    -- The registry run/enqueue/start primitives take a raw 'Connection'/'Tasks'
    -- and are engine-internal: the facade exposes the 'Executor'/'DBOS'
    -- wrappers above and the 'WorkflowCtx'-taking scoped entries below.
    -- (C5c: no facade entry hands a bare connection to a start/enqueue path.)
    Enqueue (..),
    DuplicationPolicy (..),
    enqueueNew,
    validateEnqueue,
    storedPriority,
    Timeout (..),
    timeoutBudget,
    resolveTimeoutDeadline,
    RunOptions (..),
    StartOptions (..),
    runOptionsDefault,
    startOptionsDefault,
    runOptionsToStartOptions,
    startChildWorkflow,
    -- * Task ownership (workflow.rs @Tasks@)
    Queue (..),
    QueueOptions (..),
    QueueChange (..),
    QueueConflict (..),
    defaultQueueOptions,
    registerQueue,
    queue,
    listQueues,
    updateQueue,
    deleteQueue,

    -- * Workflow messages
    IdempotencyKey (..),
    MessageUUID (..),
    NotificationRow (..),
    SendMessage (..),
    Topic (..),
    messageUUIDForSend,
    notificationRowForMessage,
    nullTopicSentinel,
  )
where

import DBOS.Transact.Checkpoint (PendingStep (..), StepDurability (..), StepPlacement (..))
import DBOS.SystemDB.Retry (SysdbEvent (..), uuidEntropy)
import DBOS.Transact.Connection ()
import DBOS.Transact.Dequeue (QueueEvent (..))
import DBOS.Transact.Datasource (DataSource (..), IsolationLevel (..), RecordedOutcome (..), TransactionConfig (..), TransactionEvent (..), Tx (..), runTransaction, runTransactionOutside, transactionConfigDefault)
import DBOS.Transact.Datasource.Postgres (AppDataSource, acquireAppDataSource, acquireAppDataSourceIn, acquireAppDataSourceInFromEnv, beginSql, releaseAppDataSource, runAppSession, toDataSource, verifyAppDataSource)
import DBOS.Transact.Client (Client (..), ClientConfig (..), EnqueueOptions (..), clientAppName, clientCancelWorkflows, clientConfigFromEnv, clientConfigNew, clientDeleteWorkflows, clientForkWorkflows, clientGetEvent, clientLatestApplicationVersion, clientListApplicationVersions, clientListWorkflows, clientOutcomePollInterval, clientPromoteVersion, clientResumeWorkflows, clientSendMessage, clientSendMessages, closeClient, connectClient, enqueueClientWorkflow, enqueueClientWorkflowWith, enqueueOptionsNew, enqueueOptionsOn, retrieveClientWorkflow, validateClientConfig, workflowStatusClient)
import DBOS.Transact.Serialization (CodecError (..), decodeWorkflowValue, encodeUnit, encodeWorkflowValue)
import DBOS.Transact.Config
  ( Config (..),
    Serializer (..),
    serializerName,
    configFromEnv,
    configNew,
    validateConfig,
  )
import DBOS.Transact.Error (DurableError, EngineOnly, Error (..), Failure (..), application, controlOf, decodeErrorText, encodeErrorText, liftEngine, mapApplication, renderTransactError)
import DBOS.Transact.Event (getEvent, pendingGetEvent, pendingSetEvent, setEvent)
import DBOS.Transact.Handle (Provenance (..), WorkflowHandle (..), awaitChild, handleResult, handleStatus, handleWorkflowId, pendingAwait, pollingHandle)
import DBOS.Transact.Identity (Environment (..), Identity (..), appVersionEnv, cloudAppNameEnv, readEnvironment, resolve, validateAppName)
import DBOS.Transact.Instance (DBOS, Executor, cancelWorkflows, clearDBOSCheckpoints, dbosAppVersion, dbosExecutorId, dequeueDBOSWorkflows, deleteWorkflows, enqueueDBOSWorkflow, fetchWorkflowStatuses, forkFrom, forkWorkflows, getWorkflowEvent, isLaunched, launch, launchOn, launchWithEnvironment, listWorkflowIdsByName, listWorkflows, newDBOS, registerDBOSDataSource, registerDBOSWorkflowRef, registerDBOSWorkflow, resumeWorkflows, retrieveWorkflow, runDBOSWorkflow, runDBOSWorkflowRef, sendWorkflowMessage, sendWorkflowMessages, setWorkflowDelay, shutdown, startDBOSWorkflowRef, updateWorkflowAttributes)
import DBOS.Transact.Management (ManagementEvent (..), cancelWorkflowsInWorkflow, deleteWorkflowsInWorkflow, forkFromInWorkflow, forkWorkflowsInWorkflow, listWorkflowsInWorkflow, resumeWorkflowsInWorkflow)
import DBOS.Transact.Context (StepCtx, StepMarker (..), StepStatus (..), WorkflowCtx, firstStepStatus, nextWorkflowMarker, nextWorkflowStepId, stepCtxCancellationToken, stepCtxId, stepCtxStatus, stepCtxWorkflow, withStep, withWorkflow, workflowCtxId)
import DBOS.Tracer (LoggerBackend (..), LogEvent (..), LogSeverity (..), SomeTracer (..), ThreadIdCache, TimedFastLogger, Tracer, acquireLoggerBackend, contramap, fastLoggerTracer, ioTracer, mkTracer, newLoggerBackend, nullTracer, parseSeverity, showSeverity, runTracer)
import DBOS.Transact.Message (Forks (..), Message (..), SendBulkOptions (..), SendOptions (..), recv, send, sendBulk, sendBulkOptionsDefault, sendBulkWith, sendOptionsDefault, sendWith)
import DBOS.Transact.Registry
  ( WorkflowKey (..),
    WorkflowRef,
    newWorkflowKey,
    registerWorkflowRef,
    Registry,
    registerTypedWorkflow,
  )
import DBOS.Transact.Recovery (EngineEvent (..))
import DBOS.Transact.Queue
  ( Queue (..),
    QueueOptions (..),
    QueueChange (..),
    QueueConflict (..),
    defaultQueueOptions,
    registerQueue,
    queue,
    listQueues,
    updateQueue,
    deleteQueue,
  )
import DBOS.Transact.Select (Branches (..), Racing (..), Recording (..), SelectArm (..), Winner (..), checkSelect, controlError, newBranches, pushBranch, recordSelect, selectStep)
import DBOS.Transact.Step (StepError (..), StepOptions (..), WorkflowEvent (..), pendingWorkflowStep, pendingWorkflowStepWith, runNestedStep, runWorkflowStep, runWorkflowStepWith, stepOptionsDefault)
import DBOS.Transact.Sleep (SleepEvent (..), pendingSleep, sleepPlain, sleepWorkflowStep)
import DBOS.Transact.Wait (WaitEvent (..), joinWorkflows, selectWorkflow, waitForFirstWorkflow, waitForWorkflow, waitForWorkflows)
import DBOS.Transact.Workflow (DuplicationPolicy (..), Enqueue (..), RunOptions (..), StartOptions (..), Tasks, Timeout (..), abortAll, childWorkflowId, enqueueNew, newTasks, resolveTimeoutDeadline, runOptionsDefault, runOptionsToStartOptions, spawnTracked, startChildWorkflow, startOptionsDefault, storedPriority, tasksSpawner, timeoutBudget, validateEnqueue)

import DBOS.SystemDB.Types (
    durationAsMillis,
    millisDuration,
    secondsDuration,
    ApplicationVersion (..),
    Duration (..),
    Serialization (..),
    SerializedWorkflowValue (..),
    Timestamp (..),
    WorkflowDelay (..),
    WorkflowId (..),
    WorkflowName (..),
    IdempotencyKey (..),
    MessageUUID (..),
    NotificationRow (..),
    SendMessage (..),
    Topic (..),
    messageUUIDForSend,
    notificationRowForMessage,
    nullTopicSentinel,
    WorkflowStatus (..),
    WorkflowStatusDecodeError (..),
    isTerminal,
    parseWorkflowStatus,
    workflowStatusText)
import DBOS.SystemDB.Error (BackendError (..))
