module DBOS.Transact
  ( -- * Workflow executions
    ApplicationVersion (..),
    Duration (..),
    durationAsMillis,
    millisDuration,
    secondsDuration,
    ExecutorId (..),
    Timestamp (..),
    WorkflowDelay (..),
    WorkflowId (..),
    WorkflowName (..),
    WorkflowStatus (..),
    WorkflowStatusDecodeError (..),
    isTerminal,
    parseWorkflowStatus,
    workflowStatusText,

    -- * Durable steps
    StepError (..),
    runWorkflowStep,
    runWorkflowStepWith,
    stepOptionsDefault,
    stepBackoff,
    StepOptions (..),
    ShouldRetry,
    sleepWorkflowStep,
    sleepPlain,
    setEvent,
    getEvent,
    Message (..),
    Forks (..),
    SendOptions (..),
    sendOptionsDefault,
    SendBulkOptions (..),
    sendBulkOptionsDefault,
    send,
    sendWith,
    sendBulk,
    sendBulkWith,
    recv,

    -- * Durable value codec
    CodecError (..),
    Serialization (..),
    SerializedWorkflowValue (..),
    decodeWorkflowValue,
    encodeAttributes,
    encodeUnit,
    encodeWorkflowValue,

    -- * Domain-event tracing (no logging library)
    Tracer,
    SomeTracer (..),
    mkTracer,
    nullTracer,
    traceWith,
    projectTracer,
    contramap,
    TimedFastLogger,
    acquireFastBackend,
    fastLoggerTracer,
    ioTracer,
    simTracer,
    LogSeverity (..),
    showSeverity,
    LogEvent (..),
    EngineEvent (..),
    SysdbEvent (..),
    WorkflowEvent (..),
    QueueEvent (..),
    ManagementEvent (..),
    withTracer,
    contextTracer,

    -- * Configuration and identity (config.rs, identity.rs)
    Config (..),
    Serializer (..),
    serializerName,
    configNew,
    configFromEnv,
    databaseUrlEnv,
    validateConfig,
    outcomePollInterval,
    defaultOutcomePollInterval,
    renderTransactError,
    Environment (..),
    Identity (..),
    appVersionEnv,
    cloudEnv,
    appIdEnv,
    cloudAppNameEnv,
    executorIdEnv,
    defaultExecutorId,
    readEnvironment,
    resolve,
    validateAppName,
    -- * Instance lifecycle (instance.rs)
    DBOS,
    newDBOS,
    isLaunched,
    dbosExecutorId,
    dbosAppVersion,
    dbosAppId,
    launch,
    launchWithEnvironment,
    shutdown,
    registerDBOSWorkflow,
    registerDBOSWorkflowRef,
    runDBOSWorkflow,
    startDBOSWorkflowRef,
    runDBOSWorkflowRef,
    enqueueDBOSWorkflow,
    retrieveWorkflow,
    getWorkflowEvent,
    sendWorkflowMessage,
    sendWorkflowMessages,
    listWorkflowIdsByName,
    fetchWorkflowStatuses,
    dequeueDBOSWorkflows,
    cancelWorkflows,
    cancelWorkflowsInWorkflow,
    resumeWorkflows,
    resumeWorkflowsInWorkflow,
    setWorkflowDelay,
    deleteWorkflows,
    deleteWorkflowsInWorkflow,
    forkWorkflows,
    forkWorkflowsInWorkflow,
    forkFrom,
    forkFromInWorkflow,
    updateWorkflowAttributes,
    listWorkflows,
    listWorkflowsInWorkflow,
    selectWorkflow,
    joinWorkflows,
    waitForWorkflow,
    waitForFirstWorkflow,
    waitForWorkflows,
    -- * Checkpoint placement (checkpoint.rs)
    StepPlacement (..),
    StepDurability (..),
    PendingStep (..),
    placementAt,
    placementHere,
    placementStepId,
    pendingStepId,
    checkHere,
    describePlacement,
    placementWhereabouts,
    insideAWorkflow,
    -- * Workflow handles (handle.rs)
    WorkflowHandle (..),
    Provenance (..),
    pollingHandle,
    handleWorkflowId,
    handleStatus,
    handleResult,
    -- * Client (client.rs)
    Client (..),
    ClientConfig (..),
    clientConfigNew,
    clientConfigFromEnv,
    validateClientConfig,
    clientOutcomePollInterval,
    connectClient,
    closeClient,
    clientAppName,
    EnqueueOptions (..),
    enqueueOptionsNew,
    enqueueOptionsOn,
    enqueueClientWorkflow,
    enqueueClientWorkflowWith,
    retrieveClientWorkflow,
    workflowStatusClient,
    clientSendMessage,
    clientSendMessages,
    clientGetEvent,
    clientCancelWorkflows,
    clientResumeWorkflows,
    clientDeleteWorkflows,
    clientForkWorkflows,
    clientListApplicationVersions,
    clientLatestApplicationVersion,
    clientPromoteVersion,
    clientListWorkflows,
    -- * Connection (connection.rs)
    Connection (..),
    Owner (..),
    SomeSystemDB (..),
    ExecutionIdentity (..),
    nextExecutionIdentity,
    generatedWorkflowId,
    uuidWorkflowId,
    uuidEntropy,
    runSystemDB,
    newConnection,
    forApplication,
    closeConnection,
    -- * Ambient context
    Ctx,
    newCtx,
    StepStatus (..),
    stepStatusId,
    stepStatusCurrentAttempt,
    stepStatusMaxAttempts,
    firstStepStatus,
    nextAttempt,
    StepScope,
    newStepScope,
    StepMarker (..),
    nextStepMarker,
    newWorkflowState,
    currentConnection,
    currentIdentity,
    executionIdentityOf,
    isSameExecution,
    nextStepId,
    withAttempt,
    workflowId,
    stepId,
    stepMarker,
    stepStatus,
    deadline,
    inStep,
    withSystemDB,
    cancellationToken,
    cancelToken,
    tokenCancelled,
    -- * Workflow registry and runner
    Error (..),
    BackendError (..),
    WorkflowKey (..),
    newWorkflowKey,
    instanceWorkflowKey,
    workflowKeyFromRow,
    renderWorkflowKey,
    WorkflowRef,
    refKey,
    refName,
    registerWorkflowRef,
    ErasedWorkflow,
    Registry,
    Snapshot,
    newRegistry,
    registerTypedWorkflow,
    registerErasedWorkflow,
    snapshotRegistry,
    thawRegistry,
    lookupSnapshotWorkflow,
    snapshotSize,
    runRegisteredWorkflow,
    runRegisteredWorkflowWithSubmission,
    runRegisteredWorkflowWithRow,
    enqueueWorkflow,
    Enqueue (..),
    DuplicationPolicy (..),
    enqueueNew,
    validateEnqueue,
    storedPriority,
    Timeout (..),
    timeoutBudget,
    resolveTimeoutDeadline,
    RunOptions (..),
    StartOptions (..),
    runOptionsDefault,
    startOptionsDefault,
    runOptionsToStartOptions,
    childWorkflowId,
    resolveEnqueueCollision,
    startWorkflowRef,
    runWorkflowRef,
    startChildWorkflow,
    -- * Task ownership (workflow.rs @Tasks@)
    Tasks,
    newTasks,
    spawnTracked,
    abortAll,
    reenqueueForRecovery,
    Queue (..),
    QueueOptions (..),
    QueueChange (..),
    QueueConflict (..),
    defaultQueueOptions,
    defaultQueueChange,
    queueFromRecord,
    queueIsPartitioned,
    queueOptionsToNewQueue,
    queueChangeToUpdate,
    validateQueueOptions,
    registerQueue,
    queue,
    listQueues,
    updateQueue,
    deleteQueue,

    -- * Workflow messages
    IdempotencyKey (..),
    MessageUUID (..),
    NotificationRow (..),
    SendMessage (..),
    Topic (..),
    messageUUIDForSend,
    notificationRowForMessage,
    nullTopicSentinel,
  )
where

import DBOS.Prelude
import DBOS.Transact.Checkpoint (PendingStep (..), StepDurability (..), StepPlacement (..), checkHere, describePlacement, insideAWorkflow, pendingStepId, placementAt, placementHere, placementStepId, placementWhereabouts)
import DBOS.SystemDB.Retry (uuidEntropy)
import DBOS.Transact.Connection (Connection (..), ExecutionIdentity (..), Owner (..), SomeSystemDB (..), closeConnection, forApplication, generatedWorkflowId, newConnection, nextExecutionIdentity, runSystemDB, uuidWorkflowId)
import DBOS.Transact.Client (Client (..), ClientConfig (..), EnqueueOptions (..), clientAppName, clientCancelWorkflows, clientConfigFromEnv, clientConfigNew, clientDeleteWorkflows, clientForkWorkflows, clientGetEvent, clientLatestApplicationVersion, clientListApplicationVersions, clientListWorkflows, clientOutcomePollInterval, clientPromoteVersion, clientResumeWorkflows, clientSendMessage, clientSendMessages, closeClient, connectClient, enqueueClientWorkflow, enqueueClientWorkflowWith, enqueueOptionsNew, enqueueOptionsOn, retrieveClientWorkflow, validateClientConfig, workflowStatusClient)
import DBOS.Transact.Serialization (CodecError (..), decodeWorkflowValue, encodeAttributes, encodeUnit, encodeWorkflowValue)
import DBOS.Transact.Config
  ( Config (..),
    Serializer (..),
    serializerName,
    configFromEnv,
    configNew,
    databaseUrlEnv,
    defaultOutcomePollInterval,
    outcomePollInterval,
    validateConfig,
  )
import DBOS.Transact.Error (Error (..), renderTransactError)
import DBOS.Transact.Event (getEvent, setEvent)
import DBOS.Transact.Handle (Provenance (..), WorkflowHandle (..), handleResult, handleStatus, handleWorkflowId, pollingHandle)
import DBOS.Transact.Identity (Environment (..), Identity (..), appIdEnv, appVersionEnv, cloudAppNameEnv, cloudEnv, defaultExecutorId, executorIdEnv, readEnvironment, resolve, validateAppName)
import DBOS.Transact.Instance (DBOS, cancelWorkflows, dbosAppId, dbosAppVersion, dbosExecutorId, dequeueDBOSWorkflows, deleteWorkflows, enqueueDBOSWorkflow, fetchWorkflowStatuses, forkFrom, forkWorkflows, getWorkflowEvent, isLaunched, launch, launchWithEnvironment, listWorkflowIdsByName, listWorkflows, newDBOS, registerDBOSWorkflow, registerDBOSWorkflowRef, resumeWorkflows, retrieveWorkflow, runDBOSWorkflow, runDBOSWorkflowRef, sendWorkflowMessage, sendWorkflowMessages, setWorkflowDelay, shutdown, startDBOSWorkflowRef, updateWorkflowAttributes)
import DBOS.Transact.Management (cancelWorkflowsInWorkflow, deleteWorkflowsInWorkflow, forkFromInWorkflow, forkWorkflowsInWorkflow, listWorkflowsInWorkflow, resumeWorkflowsInWorkflow)
import DBOS.Transact.Context (Ctx, StepMarker (..), StepScope, StepStatus (..), cancelToken, cancellationToken, contextTracer, currentConnection, currentIdentity, deadline, executionIdentityOf, firstStepStatus, inStep, isSameExecution, newCtx, newStepScope, newWorkflowState, nextAttempt, nextStepId, nextStepMarker, stepId, stepMarker, stepStatus, stepStatusCurrentAttempt, stepStatusId, stepStatusMaxAttempts, tokenCancelled, withAttempt, withSystemDB, withTracer, workflowId)
import DBOS.Tracer (EngineEvent (..), LogEvent (..), LogSeverity (..), QueueEvent (..), SomeTracer (..), SysdbEvent (..), TimedFastLogger, Tracer, acquireFastBackend, contramap, fastLoggerTracer, ioTracer, mkTracer, nullTracer, projectTracer, showSeverity, simTracer, traceWith, ManagementEvent (..), WorkflowEvent (..))
import DBOS.Transact.Message (Forks (..), Message (..), SendBulkOptions (..), SendOptions (..), recv, send, sendBulk, sendBulkOptionsDefault, sendBulkWith, sendOptionsDefault, sendWith)
import DBOS.Transact.Registry
  ( WorkflowKey (..),
    WorkflowRef,
    newWorkflowKey,
    instanceWorkflowKey,
    refKey,
    refName,
    registerWorkflowRef,
    workflowKeyFromRow,
    renderWorkflowKey,
    ErasedWorkflow,
    Registry,
    Snapshot,
    newRegistry,
    registerTypedWorkflow,
    registerErasedWorkflow,
    snapshotRegistry,
    thawRegistry,
    lookupSnapshotWorkflow,
    snapshotSize,
  )
import DBOS.Transact.Recovery (reenqueueForRecovery)
import DBOS.Transact.Queue
  ( Queue (..),
    QueueOptions (..),
    QueueChange (..),
    QueueConflict (..),
    defaultQueueOptions,
    defaultQueueChange,
    queueFromRecord,
    queueIsPartitioned,
    queueOptionsToNewQueue,
    queueChangeToUpdate,
    validateQueueOptions,
    registerQueue,
    queue,
    listQueues,
    updateQueue,
    deleteQueue,
  )
import DBOS.Transact.Step (StepError (..), StepOptions (..), ShouldRetry, runWorkflowStep, runWorkflowStepWith, stepBackoff, stepOptionsDefault)
import DBOS.Transact.Sleep (sleepPlain, sleepWorkflowStep)
import DBOS.Transact.Wait (joinWorkflows, selectWorkflow, waitForFirstWorkflow, waitForWorkflow, waitForWorkflows)
import DBOS.Transact.Workflow (DuplicationPolicy (..), Enqueue (..), RunOptions (..), StartOptions (..), Tasks, Timeout (..), abortAll, childWorkflowId, enqueueNew, enqueueWorkflow, newTasks, resolveEnqueueCollision, resolveTimeoutDeadline, runOptionsDefault, runOptionsToStartOptions, runRegisteredWorkflow, runRegisteredWorkflowWithRow, runRegisteredWorkflowWithSubmission, runWorkflowRef, spawnTracked, startChildWorkflow, startOptionsDefault, startWorkflowRef, storedPriority, timeoutBudget, validateEnqueue)

import DBOS.SystemDB.Types (
    durationAsMillis,
    millisDuration,
    secondsDuration,
    ApplicationVersion (..),
    Duration (..),
    ExecutorId (..),
    Serialization (..),
    SerializedWorkflowValue (..),
    Timestamp (..),
    WorkflowDelay (..),
    WorkflowId (..),
    WorkflowName (..),
    IdempotencyKey (..),
    MessageUUID (..),
    NotificationRow (..),
    SendMessage (..),
    Topic (..),
    messageUUIDForSend,
    notificationRowForMessage,
    nullTopicSentinel,
    WorkflowStatus (..),
    WorkflowStatusDecodeError (..),
    isTerminal,
    parseWorkflowStatus,
    workflowStatusText)
import DBOS.SystemDB.Error (BackendError (..))
